# Generated by Django 5.2.6 on 2025-11-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='branch',
        ),
    ]
