"""
Django settings for inventory_management project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j@z%a^!@+m07654321zyxwvutsrqponmlkjihgfedcba"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow hosts for Render deployment and testing
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "tecksolution.onrender.com", "testserver"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Django REST framework
    "rest_framework",
    "rest_framework.authtoken",
    "authentication",
    "dashboard",
    "products",
    "sales",
    "purchases",
    "expenses",
    "customers",
    "suppliers",
    "reports",
    "settings",
    "notifications",
    "superadmin",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this line for static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    # LocaleMiddleware should come after SessionMiddleware and before CommonMiddleware
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "superadmin.middleware.BusinessContextMiddleware",  # Add this line for multi-tenancy
    "settings.middleware.AuditLogMiddleware",  # Add this line for audit logging
    "settings.middleware.EmailSettingsMiddleware",  # Add this line for email settings
]

ROOT_URLCONF = "inventory_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "settings.context_processors.business_settings",
                "settings.context_processors.notifications",
                "settings.context_processors.media_settings",  # Add this line
                "superadmin.context_processors.current_business",  # Add this line for multi-tenancy
                # Allauth context processors
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "inventory_management.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Import database configuration from local settings
# PostgreSQL is the only supported database for this application
# SQLite fallback has been removed to ensure consistent database behavior
try:
    from .local_settings import DATABASES
except ImportError:
    # If local_settings.py is not available, try to use DATABASE_URL from environment variables
    # This is commonly used in platforms like Render
    import os
    import dj_database_url
    
    # Try to get DATABASE_URL from environment variables
    DATABASE_URL = os.environ.get('DATABASE_URL')
    
    if DATABASE_URL:
        # Parse the DATABASE_URL and configure the database
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL)
        }
    else:
        # Fallback to SQLite for development if no DATABASE_URL is provided
        # NOTE: This is NOT recommended for production use
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            }
        }
    
    # Also set default settings for development
    SECRET_KEY = 'django-insecure-default-key-for-development-only-change-in-production'
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Internationalization: supported languages
from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ("en", _("English")),
    ("rw", _("Kinyarwanda")),
    ("es", _("Espa\u00f1ol")),
    ("fr", _("Fran\u00e7ais")),
    ("de", _("Deutsch")),
]

# Path where locale files (PO/MO) will be stored
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Ensure media files are served in production
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT, exist_ok=True)

# Configure media file serving for production
if not os.environ.get("RENDER"):
    # Local development - serve media files through Django
    pass
else:
    # Production - ensure media files are properly served
    # Media files will be served by the web server (Nginx/Apache) in production
    # but we need to ensure the directory exists
    if not os.path.exists(MEDIA_ROOT):
        os.makedirs(MEDIA_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "authentication.User"

# Login/Logout URLs
LOGIN_URL = "/accounts/login/"
LOGOUT_URL = "/accounts/logout/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Ensure Django admin is not referenced accidentally
# This prevents the NoReverseMatch error for 'admin' namespace

# Email backend (using console backend for development)
# In production, you would use a real email backend like SMTP
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True
