# Generated by Django 5.2.6 on 2025-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_options_alter_expense_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='branch',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
