# Generated by Django 5.2.7 on 2025-11-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder_business'),
        ('superadmin', '0004_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='superadmin.branch'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='superadmin.business'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='superadmin.branch'),
        ),
    ]
