# Generated by Django 5.2.6 on 2025-11-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchaseitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='business',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='branch',
        ),
    ]
