# Generated by Django 5.2.8 on 2025-11-29 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
        ("superadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="superadmin.business",
            ),
        ),
    ]
