# Generated by Django 5.2.7 on 2025-11-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_business_business_type'),
    ]

    operations = [
    ]