# Generated by Django 5.2.6 on 2025-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("rw", "Kinyarwanda")],
                default="en",
                max_length=10,
                verbose_name="Preferred language",
            ),
        ),
    ]
