# Generated by Django 5.2.6 on 2025-11-03 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#3498db', max_length=7)),
                ('secondary_color', models.CharField(default='#2c3e50', max_length=7)),
                ('accent_color', models.CharField(default='#e74c3c', max_length=7)),
                ('background_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('text_color', models.CharField(default='#343a40', max_length=7)),
                ('sidebar_color', models.CharField(default='#2c3e50', max_length=7)),
                ('card_color', models.CharField(default='#ffffff', max_length=7)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('custom', 'Custom')], default='light', max_length=10)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Theme Preferences',
            },
        ),
    ]
