# Generated by Django 5.2.7 on 2025-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userthemepreference'),
        ('superadmin', '0003_alter_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='users', to='superadmin.business'),
        ),
    ]
