# Generated by Django 5.2.6 on 2025-11-18 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_remove_user_business_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_access_products", models.BooleanField(default=True)),
                ("can_access_sales", models.BooleanField(default=True)),
                ("can_access_purchases", models.BooleanField(default=True)),
                ("can_access_customers", models.BooleanField(default=True)),
                ("can_access_suppliers", models.BooleanField(default=True)),
                ("can_access_expenses", models.BooleanField(default=True)),
                ("can_access_reports", models.BooleanField(default=True)),
                ("can_access_settings", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user",)},
            },
        ),
    ]
