# Generated by Django 5.2.7 on 2025-11-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_business_alter_customer_unique_together'),
        ('superadmin', '0004_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='superadmin.branch'),
        ),
    ]
