# Generated by Django 5.2.7 on 2025-11-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_cart_options_alter_cartitem_unique_together_and_more'),
        ('superadmin', '0004_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='superadmin.branch'),
        ),
        migrations.AddField(
            model_name='refund',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='superadmin.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='superadmin.branch'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='superadmin.branch'),
        ),
    ]
