# Generated by Django 5.2.6 on 2025-11-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_cart_created_by_cartitem_created_by_and_more'),
        ('superadmin', '0003_alter_business_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='created_by',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='superadmin.business'),
        ),
    ]
