# Generated by Django 5.2.8 on 2025-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productvariant_variantattribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_variants",
            field=models.BooleanField(default=False),
        ),
    ]
