# Generated by Django 5.2.6 on 2025-11-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_stockalert_stockmovement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockalert",
            name="business",
        ),
        migrations.RemoveField(
            model_name="stockalert",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stockalert",
            name="resolved_by",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="business",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="product",
        ),
        migrations.DeleteModel(
            name="StockAdjustment",
        ),
        migrations.DeleteModel(
            name="StockAlert",
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
    ]
