# Generated by Django 5.2.6 on 2025-11-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stockalert_stockmovement'),
    ]

    operations = [
        # This migration is empty because all the necessary changes
        # were already implemented in the previous migration.
        # This file exists to maintain proper migration sequence.
    ]