# Generated by Django 5.2.7 on 2025-11-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_unit_options_alter_product_unique_together_and_more'),
    ]

    operations = [
    ]
