# Generated by Django 5.2.6 on 2025-11-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20251117_2011'),
        ('products', '0005_add_stock_adjustment_model'),
    ]

    operations = [
    ]
