# Generated by Django 5.2.6 on 2025-11-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20251104_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku',)},
        ),
    ]
