# Generated by Django 5.2.6 on 2025-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_unique_together'),
        ('superadmin', '0003_alter_business_business_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'sku')},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode_format',
            field=models.CharField(choices=[('code128', 'Code 128 (High Density)'), ('ean13', 'EAN-13 (Retail Standard)'), ('upca', 'UPC-A (Retail Standard)')], default='code128', max_length=20),
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
